### ISSUE TITLE
Plan Yeet Haus Event

### ISSUE THREAD

**Issue by TravisWyche** [yeet-haus/dao#11]
We were thinking something at the Lion's Lair. The idea of a hot dog cart was proposed. What needs to happen to push this forward?

**Comment by skuhlmann** [comment]
had a sidebar with tae - what if we team with RG and whoever and yeet for a lions liar bar tab + some lotto tickets + a carton of cigs.

**Comment by earth2travis** [comment]
- Variety of ideas
- Combine with Season 4 from RG
- Foamies for homies
- Who cares?
- Needs owner
- DAOhaus Live Live guerilla worked well last year
- Let the date emerge from the group
- What are the periods?
- Yeet into bar tab
- Make campaign clear and cool
- Good project to demonstrate project
- Monday (the 26th) before ETH Denver
- Make sure the have DAI in treasury
