### ISSUE TITLE
Configure `yeet.haus` Subdomains

### ISSUE THREAD

**Issue by TravisWyche** [yeet-haus/dao#22]
Will need to connect domain registrar, Cloudflare, and Vercel

- `yeet.haus`
- `app.yeet.haus`
- `dao.yeet.haus`
- `docs.yeet.haus`

https://vercel.com/docs/integrations/cloudflare

**Comment by earth2travis** [comment]
## `bootleggers.wtf`

![Image](https://github.com/yeet-haus/dao/assets/522182/ea128da6-83b7-49ea-8db3-7af3fefce002)

## `yeet.haus`

![Image](https://github.com/yeet-haus/dao/assets/522182/094bbc91-3fb8-4ccd-acc9-eb94be42038e)

**Comment by earth2travis** [comment]
@TravisWyche please update the nameservers with our domain registrar

## Cloudflare Nameservers

- `elisa.ns.cloudflare.com`
- `quincy.ns.cloudflare.com`

And provide the MX records that need to be added for Proton Mail

**Comment by earth2travis** [comment]
Was hoping to knock this configuration out this weekend but it looks like the nameservers still need to be updated. It can take up to 24 hours to propagate once the changes are made.

**Comment by earth2travis** [comment]
> If I switch the DNS to nameservers it will break our email config.

That is why I asked for the MX records too

> And provide the MX records that need to be added for Proton Mail

Cloudflare is our DNS provider. The registrar where the domain was purchased needed to point to the DNS servers

**Comment by earth2travis** [comment]
## Site

![Image](https://github.com/yeet-haus/dao/assets/522182/7a4b58e5-0d22-4b36-9053-a1ef3aff7246)

## App

![Image](https://github.com/yeet-haus/dao/assets/522182/429f1320-0abd-4ec5-a0f2-2c7e02679588)

## Docs

![Image](https://github.com/yeet-haus/dao/assets/522182/d5efb3f5-87df-4448-8525-92850c268fd4)

## DAO

![Image](https://github.com/yeet-haus/dao/assets/522182/95acba0f-9811-46ed-b792-cbb1d649b60f)

**Comment by earth2travis** [comment]
Root and subdomains added to Cloudflare

![Image](https://github.com/yeet-haus/dao/assets/522182/2481a882-9e5e-468f-b23f-a4ae97920082)

**Comment by earth2travis** [comment]
Waiting on verification of `yeet.haus` with Proton Mail

**Comment by earth2travis** [comment]
Updates made in Proton Mail

![Image](https://github.com/yeet-haus/dao/assets/522182/9a346be4-64c0-48d5-96ab-662b8753ad8d)

![Image](https://github.com/yeet-haus/dao/assets/522182/91a71644-04ea-4581-8815-05241cfdb59e)

## Todo

- [ ] test email
- [ ] See if SPF and DKIM go green

**Comment by earth2travis** [comment]
Every fing time: [How do I resolve "err_too_many_redirects" when using a Cloudflare proxy with Vercel?](https://vercel.com/guides/resolve-err-too-many-redirects-when-using-cloudflare-proxy-with-vercel)

- [x] Set SSL/TLS encryption mode to Full (strict)

**Comment by earth2travis** [comment]
![Image](https://github.com/yeet-haus/dao/assets/522182/8997d26e-3a1d-43ca-9a1e-341e4fdbc0d4)

**Comment by earth2travis** [comment]
![Image](https://github.com/yeet-haus/dao/assets/522182/75d5fc0f-c5d1-4cd8-93b8-137f6ef6aeff)
