### ISSUE TITLE
Deploy Gnosis Safes to Networks

### ISSUE THREAD

**Issue by earth2travis** [yeet-haus/dao#23]
Deploy a Gnosis Safe with the same address to multiple networks

https://github.com/yeet-haus/dao/wiki/Safes

- Arbitrum: ✅
- Optimism: ✅
- Base: ✅
- Zora: 
- Mainnet: ✅
- Gnosis Chain: ✅
- Sepolia: ✅

These wallets will be used as sidecar safes for protocol fees

Steps: [Multichain Gnosis Safe](https://hackmd.io/Zz--iSq-Rl6apEMSl0hA1w)

- [x] Create Safes
- Add to DAO <-- cannot add cross-chain safes to DAO
- [x] Add other signers
- [x] Change threshold to 2/3

**Comment by earth2travis** [comment]
Deployed a new Gnosis Safe on Gnosis Chain https://gnosisscan.io/tx/0x97ac1f3aafffb719907384c6e9f1515c6f9d90ea6d402254d150737c078655ff/

But could not find the `GnosisSafeProxyFactory` and the raw input to deploy on other networks. According to Dekan it used a relayer and Galato actually ran the transaction.

**Comment by earth2travis** [comment]
Another one starting with Arbitrum: https://arbiscan.io/tx/0x787ef4c61b028e9e217c1a176438c28624884e159c3e7032b277e8ceba65d1c3

Here is the wallet address

`0xD0f8720846890a7961945261FE5012E4cA39918e`

**Comment by earth2travis** [comment]
- Arbitrum: ✅
- Optimism: ✅
- Base: ✅
- Zora
- Mainnet
- Gnosis Chain: ✅

Zora is done but may not be supported by the Gnosis Safe app yet.

Will wait for gas to go down a little for Mainnet

**Comment by earth2travis** [comment]
## Arbitrum

- Transaction: https://arbiscan.io/tx/0x787ef4c61b028e9e217c1a176438c28624884e159c3e7032b277e8ceba65d1c3
- Safe: https://app.safe.global/transactions/history?safe=arb1:0xD0f8720846890a7961945261FE5012E4cA39918e

## Optimism

- Transaction: https://optimistic.etherscan.io/tx/0x240538c9131de23b243a20c29b1de033138f501d2bf6e2c717a923a134ee4792
- Safe: https://app.safe.global/transactions/history?safe=oeth1%3A0xD0f8720846890a7961945261FE5012E4cA39918e

## Base

- Transaction: https://basescan.org/tx/0xbeb58eca16851c84560a9618576810aa15a6cd66f052104c2275c3b1080ae337
- Safe: https://app.safe.global/settings/setup?safe=base1:0xD0f8720846890a7961945261FE5012E4cA39918e

## Zora

- Transaction: https://explorer.zora.energy/tx/0xf700c8e0664d2b6ae4dc3e659bcdec76d1c6e95a607f3b32eecd006ccbbf2c25
- Safe (not currently supported): https://app.safe.global/home?safe=zora:0xD0f8720846890a7961945261FE5012E4cA39918e

## Polygon

- Transaction: https://polygonscan.com/tx/0x1d54b864c58914a08b33887614364a0c5168ebdffbbb47451d444ebfd4d23b8b
- Safe: https://app.safe.global/home?safe=matic:0xD0f8720846890a7961945261FE5012E4cA39918e

## Gnosis Chain

- Transaction: https://gnosis.blockscout.com/tx/0xc1cf076d7c547d2aec7dcdd55ff2712f5eb815fd3af8b112f6d1deec93a194f1
- https://app.safe.global/home?safe=gno:0xD0f8720846890a7961945261FE5012E4cA39918e

## Mainnet

**Comment by skuhlmann** [comment]
@earth2travis when will you be doing sepolia?

**Comment by skuhlmann** [comment]
well - we might not need the safe - can just burn these fees. 

nevermind

**Comment by earth2travis** [comment]
## Sepolia

- Transaction: https://sepolia.etherscan.io/tx/0x89e51117c1c136a93901661aad43be1d39fb0d2ec16dc58d14698a41d58ba913
- Safe: https://app.safe.global/home?safe=sep:0xD0f8720846890a7961945261FE5012E4cA39918e

@skuhlmann

**Comment by earth2travis** [comment]
## Mainnet

- Transaction: https://etherscan.io/tx/0x3d4240b0e5e884aa803f08e5682e582c243300fc6d035ac08951b8bed8deb35a
- Safe: https://app.safe.global/home?safe=eth:0xD0f8720846890a7961945261FE5012E4cA39918e

**Comment by earth2travis** [comment]
- [x] Added Sam and TW and updated the threshold to 2 of 3 on Arbitrum: https://app.safe.global/settings/setup?safe=arb1:0xD0f8720846890a7961945261FE5012E4cA39918e
- [x] Added Sam and TW and updated the threshold to 2 of 3 on Optimism: https://app.safe.global/settings/setup?safe=oeth:0xD0f8720846890a7961945261FE5012E4cA39918e
- Base:
- Zora: Not Supported by Gnosis (AFIK)
- Polygon: 
- [x] Added Sam and TW and updated the threshold to 2 of 3 on Gnosis Chain: https://app.safe.global/settings/setup?safe=gno:0xD0f8720846890a7961945261FE5012E4cA39918e
- [x] Added Sam and TW and updated the threshold to 2 of 3 on Sepolia: https://app.safe.global/settings/setup?safe=sep:0xD0f8720846890a7961945261FE5012E4cA39918e
- Mainnet

Some weird shit going on on Base

![Image](https://github.com/yeet-haus/dao/assets/522182/5755892c-e55a-42cb-a4ee-a865dc4d853f)

Some weird shit going on on Polygon

![Image](https://github.com/yeet-haus/dao/assets/522182/b9d9c7f9-45a2-42bb-90ab-5f5d48b49cff)

**Comment by earth2travis** [comment]
Still need to do:

- Base
- Polygon
- Mainnet

**Comment by earth2travis** [comment]
- [x] Added [Sam](https://etherscan.io/tx/0x3ee46b0654fb612970d5c5b45b69b741acacc14880aa4f3657444e58bfa84809) and [TW](https://etherscan.io/tx/0x09c9666ab817624913fee9b44bd63c2b7093249edf8625624b7fe32014b22795) and updated the threshold to 2 of 3 on Mainnet: https://app.safe.global/settings/setup?safe=eth:0xD0f8720846890a7961945261FE5012E4cA39918e
- [x] Added [Sam](https://polygonscan.com/tx/0xa17ebbeecae5351beef90c4593893e5a9f9d1996c8cac62551173185a6ff8287) and [TW](https://polygonscan.com/tx/0x57df6d3d5ee7e17c74be085751432e49f8bdb249f82c61ea16934d9cc4130f6a) and updated the threshold to 2 of 3 on Polygon: https://app.safe.global/settings/setup?safe=matic:0xD0f8720846890a7961945261FE5012E4cA39918e

Still getting the same errors on Base

**Comment by iainnash** [comment]
https://safe.optimism.io/ supports zora

**Comment by earth2travis** [comment]
> https://safe.optimism.io/ supports zora

Good to know @iainnash. Thanks. We are not supporting Zora for the time being but it would be cool once we add some NFT features

**Comment by earth2travis** [comment]
- [x] Added [Sam](https://basescan.org/tx/0x61f677f3dccec7423df2c8e8b6b56f4c4dcea4d39862cd143be3137e84fc8821) and [TW](https://basescan.org/tx/0x667a68d4820bbf260656bfde7c37ae3fb21d63cd2f3776beecb6d1db11441024) and updated the threshold to 2 of 3 on Base: https://basescan.org/tx/0xaf2307365d81df9ae6531efdf51c5758240fbd5e54d41b0ecc0c34ee8810cd00

**Comment by earth2travis** [comment]
2/3 Safes in place on supported networks
